"use client";
import {
  OathLine,
  Bold,
  BulletList,
  Category,
  Divider,
  EyebrowLabel,
  Item,
  OOC,
  ParagraphList,
  ParaItem,
  Spoiler,
  BbLink,
  WarningCallout,
} from "@/app/(routes)/divisions/ftd/paperwork/lib/phase-notes/primitives";
import { Clock } from "lucide-react";
/**
 * The ReinstatementCertPassed guide, built from `docs/handbook/reinstatement/reinstatement-certification.txt`.
 *
 * Generated by `npm run notes:build` from that section - edit the handbook,
 * not this file, and run the command again. `npm run notes:check` fails when
 * this Guide has fallen behind the section it is drawn from.
 */
export function ReinstatementCertPassedNotes() {
  return (
    <div className="space-y-2.5">
      <div className="rounded-md border border-border/60 bg-muted/30 px-4 py-2.5">
        <EyebrowLabel icon={Clock}>
          Certification - Requirement: Junior Paramedic+, 1:30h minimum / 3h maximum
        </EyebrowLabel>
      </div>
      <WarningCallout>
        <Bold>THE REINSTATEE SHOULD HANDLE EVERYTHING</Bold>
      </WarningCallout>
      <Divider />
      <Divider />
      <ParagraphList>
        <ParaItem><Bold>Beginning</Bold></ParaItem>
      </ParagraphList>
      <BulletList>
        <Item>Make sure the reinstatee knows how to handle and transport a 10-15 if they have not handled one during the reinstatement program. If necessary, create a mock-up scenario.</Item>
        <Item>Inform the reinstatee&apos; that during this certification they are on their own.</Item>
        <Item>Ensure the reinstatee creates the unit for the certification. (D-6Z, C-2Z, B-2Z, A-1Z etc...)</Item>
      </BulletList>
      <Category title="During examination" ordered>
        <Item>Pay attention to their communication, locking their ambulance, radio calls, scene management, and treatment.</Item>
        <Item>Ensure the reinstatee&apos; attends a department radio call and is able to communicate and efficiently deal with the hectic situation it can become.</Item>
      </Category>
      <Category title="Ending certification" ordered>
        <Item>Give the reinstatee&apos; their certification result and the feedback you gathered whilst supervising them.</Item>
        <Item>Make sure they have a medical license, and offer them a Pager (optional to take it) <OOC>Don&apos;t forget the discord role!</OOC></Item>
        <Item>Inform the reinstatee&apos; regarding duty reports being optional but are encouraged to fill one out.</Item>
        <Item>Infrom the reinstatee&apos; regarding the divisions we have and that they&apos;re eligible to join, and encourage them to join a few.</Item>
        <Item>Complete certification paperwork alongside handing the reinstatee&apos; their new rank and callsign (let them pick) within LSEMS. (The rank is predetermined and is stated in the top post)</Item>
        <Item>Post the EMR/REINSTATEE Promotion Checklist on their personnel profile</Item>
      </Category>
      <Category title="Useful Links" ordered>
        <Item><BbLink href="https://gov.eclipse-rp.net/viewtopic.php?f=597&t=9497">Staff Roster</BbLink></Item>
        <Item><BbLink href="https://gov.eclipse-rp.net/ucp.php?i=ucp_groups&mode=manage">Groups</BbLink></Item>
        <Item><BbLink href="https://gov.eclipse-rp.net/viewforum.php?f=605">Personnel Files</BbLink></Item>
        <Item><BbLink href="https://gov.eclipse-rp.net/viewtopic.php?t=74487">Promotion Checklist (Supervisor Handbook Section 5</BbLink></Item>
      </Category>
      <Spoiler title="Hippocratic Oath">
        <ParagraphList>
          <ParaItem>Before handing the EMR their EMT badge, have them swear the Hippocratic Oath found below.</ParaItem>
        </ParagraphList>
        <Spoiler>
        <ParagraphList>
            <OathLine>I, FName LName, swear to fulfill, to the best of my ability and judgment, this covenant:</OathLine>
            <OathLine>I will respect the hard-won scientific gains of those who walked the steps I walk now,</OathLine>
            <OathLine>and gladly share such knowledge as is mine with those who are to follow.</OathLine>
            <OathLine>I will apply, for the benefit of the sick, all measures which are required to better</OathLine>
            <OathLine>their condition.</OathLine>
            <OathLine>I will remember that there is an art to medicine as well as science, and that warmth, sympathy,</OathLine>
            <OathLine>and understanding may outweigh the surgeon&apos;s knife or the chemist&apos;s drug.</OathLine>
            <OathLine>I will never be ashamed to say &quot;I know not,&quot; nor will I fail to call in my colleagues</OathLine>
            <OathLine>when the skills of another are needed for a patient&apos;s recovery.</OathLine>
            <OathLine>I will respect the privacy of my patients, for their problems are not disclosed to me</OathLine>
            <OathLine>that the world may know.</OathLine>
            <OathLine>I will remember that I do not treat a chart or simulation, but a sick or injured human being,</OathLine>
            <OathLine>whose illness may affect the person&apos;s family and economic stability.</OathLine>
            <OathLine>I will prevent disease whenever I can, for prevention is preferable to cure.</OathLine>
            <OathLine>I will remember that I remain a member of society, with special obligations to all my fellow</OathLine>
            <OathLine>human beings, those sound of mind and body as well as the infirm.</OathLine>
            <OathLine>If I do not violate this oath, may I enjoy life, respected while I live and remembered</OathLine>
            <OathLine>with affection thereafter.</OathLine>
            <OathLine>If I do not violate this oath, may I long experience the joy of healing those who seek my help.</OathLine>
          </ParagraphList>
        </Spoiler>
      </Spoiler>
      <Spoiler title="EMT E-mails">
        <ParagraphList>
          <ParaItem><BbLink href="https://pastebin.com/raw/EjBDfT9X">Here you&apos;ll find a list for each EMT e-mail.</BbLink> Use the correct one!</ParaItem>
        </ParagraphList>
      </Spoiler>
      <Spoiler title="Diploma Passed">
        <ParagraphList>
          <ParaItem><BbLink href="https://gov.eclipse-rp.net/viewtopic.php?p=445130#p445130">Formats found here - Promotion Posts</BbLink></ParaItem>
        </ParagraphList>
      </Spoiler>
    </div>
  );
}
