"use client";
import {
  Bold,
  BulletList,
  Divider,
  EyebrowLabel,
  Item,
  ParagraphList,
  ParaItem,
  Spoiler,
  WarningCallout,
} from "@/app/(routes)/divisions/ftd/paperwork/lib/phase-notes/primitives";
import { Clock } from "lucide-react";
/**
 * The ReinstatementPhase2 guide, built from `docs/handbook/reinstatement/reinstatement-phase-ii.txt`.
 *
 * Generated by `npm run notes:build` from that section - edit the handbook,
 * not this file, and run the command again. `npm run notes:check` fails when
 * this Guide has fallen behind the section it is drawn from.
 */
export function ReinstatementPhase2Notes() {
  return (
    <div className="space-y-2.5">
      <div className="rounded-md border border-border/60 bg-muted/30 px-4 py-2.5">
        <EyebrowLabel icon={Clock}>
          Reinstatement Phase II - Requirement: EMT-A+, 1:30h minimum / 3h maximum
        </EyebrowLabel>
      </div>
      <WarningCallout>
        <Bold>THE REINSTATEE SHOULD HANDLE EVERYTHING</Bold>
      </WarningCallout>
      <Divider />
      <Divider />
      <BulletList>
        <Item>The Reinstatement Phase II is something similar to a regular Pre-Certification within the Field Training Program.</Item>
        <Item>
          You are allowed to answer questions that the reinstatee may have, and you should be asking the reinstatee random things throughout the Phase to ensure they have retained their knowledge during their absence.
          <Spoiler title="What to look out for:">
            <ParagraphList>
              <ParaItem>Did the EMR create a unit? Did the EMR start service correctly? Did the EMR park their ambulance correctly in the ambulance bay? Did the EMR check if there are any calls to take from the call list? Did the EMR respond to calls without you asking to do it? Did the EMR follow call priority? Did the EMR manage to use radio calls properly? Did the EMR respond to department radio if there were any department calls? Did the EMR handle department radio properly and timely? Did the EMR handle PD/SD calls properly? Did the EMR use our MD frequency to radio that they responding to PD/SD calls? Did the EMR ask if the patient is a 10-15 or 10-16? Did the EMR ask if any treatment has been done before? Did the EMR ask if they clear to load the patient to an ambulance if the patient was 10-15? Did the EMR ask PD/SD where they want to go? Did the EMR properly radio transporting a 10-15 Did the EMR ask PD/SD if they clear to drop patients at MD? Did the EMR keep their ambulance locked at all times? Did the EMR properly utilize code 2, 3 and 4? Did the EMR drive properly? Did the EMR know how to utilize all necessary radio calls and codes throughout? Did the EMR treat properly and timely? Did the EMR roam properly and safely?</ParaItem>
            </ParagraphList>
          </Spoiler>
        </Item>
        <Item>The Reinstatement Phase II must be flawless. Any major mistakes are eliminatory and will result in a failed Phase, and will have to be attempted again.</Item>
        <Item>After the Phase is completed, the EMR can go on duty as an EMR unit, exactly the same as after passing the FTP Pre-Certification.</Item>
      </BulletList>
    </div>
  );
}
