"use client";
import {
  Bold,
  BulletList,
  Category,
  Divider,
  Em,
  EyebrowLabel,
  Item,
  OOC,
  ParagraphList,
  ParaItem,
  BbLink,
} from "@/app/(routes)/divisions/ftd/paperwork/lib/phase-notes/primitives";
import { Clock } from "lucide-react";
/**
 * The Introduction guide, built from `docs/ftp/regular/introduction.txt`.
 *
 * Generated by `npm run notes:build` from that section - edit the FTP,
 * not this file, and run the command again. `npm run notes:check` fails when
 * this Guide has fallen behind the section it is drawn from.
 */
export function IntroductionNotes() {
  return (
    <div className="space-y-2.5">
      <div className="rounded-md border border-border/60 bg-muted/30 px-4 py-2.5">
        <EyebrowLabel icon={Clock}>
          INTRODUCTION - EMT-I+
        </EyebrowLabel>
      </div>
      <Divider />
      <Divider />
      <Category title="Uniform and On Duty" ordered>
        <Item>Let the EMR know that they <Bold>cannot</Bold> be on duty without a trainer. Make sure they understand this. If they cannot find a trainer by using the radio then direct them to the Student area.</Item>
        <Item><OOC>Inform them that they must first reach out in /r for an FTO and if they have no luck then they can also reach out on the MD discord in the #fto-availability channel using the copy paste provided.</OOC></Item>
        <Item>Bring the EMR into our locker room and show them where their locker is and provide them with their uniform, bodycam and ALS bag.</Item>
        <Item><OOC>Explain how to use the /FL command, and the surrounding RP. Make sure they know they must RP pulling out equipment as well as putting it back.</OOC></Item>
        <Item>We are required to wear body cams on duty, and they are provided by LSEMS. Make sure the EMR is aware that they must have a bodycam running when on shift, at all times and demonstrate how to do so correctly. <OOC>Educate them on Bodycam RP rules, and explain that you will need to RP putting one on but you are not required to use recording software. If you can record, it is recommended but not required.</OOC></Item>
        <Item><OOC>Let them know that they do NOT have access to everything they see in the uniform menu. They can only wear uniforms that they ICly have access to.</OOC></Item>
        <Item>Let them know that if they change their name at all for any reason then they MUST notify Command and High Command</Item>
        <Item><Bold>Inform the EMR, if they are detained and arrested, they must notify Command and High Command immediately with what they were charged with.</Bold> Please have the EMR repeat this back to you.</Item>
        <Item>Let them know that if they are IA&apos;ed for any reason, they cannot talk to <Bold>anyone</Bold> about it. They can only speak to those handling the IA report when asked directly about the report.</Item>
        <Item><OOC>IA reports cannot be talked about OOC as well, about an IC IA report nor an OOC IA report.</OOC></Item>
        <Item>Inform the EMR of the social media policy: no livestreaming and/or donating to livestreams on duty and if you are distracted by your phone, do not use it on duty.</Item>
      </Category>
      <Category title="Unit Management" ordered>
        <ParagraphList>
          <ParaItem>Explain the following to the EMR:</ParaItem>
        </ParagraphList>
        <BulletList>
          <Item>How to create a unit <OOC>/createunit [name]</OOC></Item>
          <Item>Renaming the unit <OOC>/renameunit [name]</OOC></Item>
          <Item>Disbanding the unit <OOC>/disbandunit</OOC></Item>
          <Item>Joining a unit <OOC>/joinunit [name]</OOC></Item>
          <Item>Leaving a unit <OOC>/leaveunit</OOC></Item>
        </BulletList>
        <Item>Have the EMR create the unit, but make sure they ran through all four of the above at least once. And let them know that they will be creating the unit from here on out.</Item>
        <Item>Inform the EMR that there can be a maximum of 2 medics per unit, FTP callsigns and high command are exempt from this rule.</Item>
      </Category>
      <Category title="Callsigns" ordered>
        <Item>Shortly explain to the EMR how our rank system works.</Item>
        <Item>
          Inform the EMR about the existence of Zulu (Z), Echo (E), Delta (D), Oscar (O), Charlie (C), Bravo (B), and Alpha (A).
          <BulletList>
            <Item><Bold>Zulu</Bold>- Training Units Z-11, D-1Z, O-1Z, C-1Z, B-1Z, A-1Z</Item>
            <Item><Bold>Echo</Bold>- EMTs (EMT-B/I/A/P)</Item>
            <Item><Bold>Delta</Bold>- Master EMT</Item>
            <Item><Bold>Oscar</Bold>- Supervisors-in-training (Junior Paramedic)</Item>
            <Item><Bold>Charlie</Bold>- Supervisors (Paramedic/Senior Paramedic/Lead Paramedic)</Item>
            <Item><Bold>Bravo</Bold>- Command (Lieutenant/Captain/Commander)</Item>
            <Item><Bold>Alpha</Bold>- High Command (Deputy Chief, Assistant Chief, Chief of EMS)</Item>
          </BulletList>
        </Item>
        <Item>Explain to the EMR that the highest-ranked medic on a scene is the scene leader.</Item>
        <Item>Explain that callsigns range from Echo-11 to Echo-99, whilst Delta and Charlie callsigns range from 1-10 or as necessary.</Item>
        <Item>Remind the EMR that they cannot leave a scene without first acquiring permission from whoever is scene leader.</Item>
        <Item>
          Inform the EMR about the existence of divisional callsigns
          <BulletList>
            <Item><Bold>AMU</Bold>- Advanced Medical Unit</Item>
            <Item><Bold>BLS</Bold>- Basic Life Support</Item>
            <Item><Bold>PR</Bold>- Public Relations</Item>
            <Item><Bold>RED</Bold>- Recruitment and Employment</Item>
            <Item><Bold>ENG</Bold>- Fire Engine</Item>
            <Item><Bold>FIRE</Bold> - Fire unit</Item>
            <Item><Bold>EVAC</Bold>- Air unit</Item>
            <Item><Bold>RSC</Bold>- Kamacho unit</Item>
            <Item><Bold>LFG</Bold>- Lifeguard</Item>
            <Item><Bold>FOR</Bold>- Forensics</Item>
          </BulletList>
        </Item>
      </Category>
      <Category title="Radio" ordered>
        <Item>Explain to the EMR that they always have to be on MD frequency while on duty.</Item>
        <Item>Inform them that we respect each other on the radio and if someone is speaking we don&apos;t <Bold>interrupt!</Bold> Teach them how to react when they hear someone speaking at the same time.</Item>
      </Category>
      <Category title="On Duty Equipment" ordered>
        <Item>Inform the EMR that they are given service equipment and that it is not to be used inappropriately.</Item>
        <Item>Inform the EMR that any form of abuse of service equipment is punishable and could lead to dismissal from the department if serious enough.</Item>
        <Item>Inform the EMR that any personal weapon or tool is to be left at home or personal vehicle.</Item>
        <Item>Inform the EMR that Kevlar is available after their Certification, and that they will have one available in their vehicles at all times. It is only to be worn in (potential) hostile or life-threatening situations, and can be requested by the most senior on shift.</Item>
      </Category>
      <Category title="Pillbox Hospital Tour" ordered>
        <Item><Bold>Vending machines(Ward D)</Bold>: Take the EMR into Ward D and show them where to find the vending machine (first door on the right). Inform the EMR that anything acquired from this vending machine is for <Bold>LSEMS Staff</Bold> only.</Item>
        <Item><Bold>Morgue</Bold>: Inform the EMR that the Morgue is to remain <Bold>LOCKED</Bold> at all times.</Item>
        <Item>
          <Bold>Employee Parking</Bold>:
          <BulletList>
            <Item>Show the EMR how to lock/unlock the gates. Explain that this is for on duty staff only. Off duty employee&apos;s with a vehicle here will be towed and secure impounded if the leadership team deems it necessary.</Item>
            <Item>Explain to the EMR that the employee parking only keeps the vehicle safe. No valuables should be kept in the vehicle as the location is susceptible to lock pickers. <Em>If a vehicle has valuables stored, parking at Legion Parking would be recommended instead.</Em></Item>
          </BulletList>
        </Item>
        <Item>Inform the EMR that all doors that are accessible by the public are to be kept <Bold>locked</Bold> at all times.</Item>
      </Category>
      <Category title="Hospitals" ordered>
        <Item>Show the EMR where to drop off at Upper Pillbox, then Lower Pillbox</Item>
        <Item>Roam to Paleto MD, and explain how to perform a drop off at Paleto MD (through the right side where the entrance of the building is, driving around to the exit on the left)</Item>
        <Item>Take the EMR inside Paleto MD, showing them where they could clock on, as well as where the plastic surgeon is located.</Item>
        <Item>Inform the EMR that if they wish to clock on at Paleto MD, they should park their vehicle at Paleto Parking, as it is unsafe to park at Paleto MD.</Item>
      </Category>
      <Divider />
      <Divider />
      <Category title="OOC Corruption + Faction Commands" ordered>
        <Item><OOC>Explain the OOC corruption ruling that LSEMS has in place to the EMR. Inform them we don&apos;t require IC evidence to terminate due to any illegal activities.</OOC></Item>
        <Item><OOC>Explain that faction-related commands are a privilege and not given out to mess around with. Explain that they cannot use the commands without first doing the applicable roleplay before using the command. If found to have done so it can lead to Faction repercussions and/or server punishments.</OOC></Item>
        <Item><OOC>Explain that much like faction commands, faction equipment and vehicles also follow the same consequences as commands.</OOC></Item>
        <Item><OOC>Explain that if they receive an admin punishment that they MUST tell High Command within 48 hours. Let them know that they need to send the link to the report and to inform High Command when it is concluded along with the result.</OOC></Item>
        <Item><OOC>Let them know that in the event that they cannot post an LOA for OOC reasons then they should reach out to someone from Command or High Command to let them know.</OOC></Item>
      </Category>
      <Divider />
      <Divider />
      <Category title="Ending Introduction" ordered>
        <Item>Tell the EMR they can use the radio to attempt to reach a certified Field Training Officer for training and teach them how to do it.</Item>
        <Item>Example: &quot;EMR Smith to dispatch, are there any available FTOs?&quot; <OOC><Bold>NO VOIP RADIO</Bold></OOC></Item>
        <Item>Inform them that they have a mandatory <Bold>30</Bold> minute break between the introduction and phase I. <Bold>Explain to them they should go over their introduction email once more to fully grasp all the information they&apos;ve been given.</Bold></Item>
        <Item>Encourage the EMR to fill out a duty report once a week. Although not required, it does help supervisors see your work.</Item>
        <Item>If you want you can take the EMR on a ride-along or ask someone else if they can take them if they want to see how it works.</Item>
        <Item><Bold>Before proceeding to do your paperwork, check if the EMR has received the Introduction email. If not, send the EMR the Introduction email:</Bold> <BbLink href="https://pastebin.com/raw/gq687baN">Introduction E-mail</BbLink></Item>
      </Category>
      <Divider />
      <Divider />
    </div>
  );
}
