"use client";
import {
  Bold,
  BulletList,
  Category,
  Command,
  Divider,
  Em,
  EyebrowLabel,
  Item,
  OOC,
  ParagraphList,
  ParaItem,
  SubHeading,
  Underline,
  BbLink,
} from "@/app/(routes)/divisions/ftd/paperwork/lib/phase-notes/primitives";
import { Clock } from "lucide-react";
/**
 * The Phase2 guide, built from `docs/ftp/regular/phase-2.txt`.
 *
 * Generated by `npm run notes:build` from that section - edit the FTP,
 * not this file, and run the command again. `npm run notes:check` fails when
 * this Guide has fallen behind the section it is drawn from.
 */
export function Phase2Notes() {
  return (
    <div className="space-y-2.5">
      <div className="rounded-md border border-border/60 bg-muted/30 px-4 py-2.5">
        <EyebrowLabel icon={Clock}>
          PHASE 2 - EMT-I+, 1 Hour 15 Min Minimum/2 Hour 30 Min Maximum
        </EyebrowLabel>
      </div>
      <ParagraphList>
        <ParaItem><Bold>THE EMR SHOULD BEGIN TREATMENT OF PATIENTS NEAR THE END OF PHASE 2 AND MANAGING THEIR UNIT</Bold></ParaItem>
      </ParagraphList>
      <Divider />
      <Divider />
      <Category title="Volatile Patient List" ordered>
        <Item>Inform the EMR of the <BbLink href="https://gov.eclipse-rp.net/viewtopic.php?p=769876">Volatile Patient List</BbLink></Item>
        <Item>Let them know that they should check this list OFTEN as it can be updated frequently.</Item>
        <Item>Emphasize that PD/SD response, OR a 10-70 from MD, is REQUIRED.</Item>
        <Item><Underline>Emphasize that individuals on this list are to be handled with extreme caution.</Underline></Item>
        <Item>Tell the EMR that they can reach out to anyone from the leadership team if they believe a name should be added.</Item>
        <Item>Elaborate on the previous point, explicitly stating that the list is reserved for those who may pose a direct threat to LSEMS as a whole.</Item>
      </Category>
      <Category title="Hostile Situations" ordered>
        <Item>Inform the EMR that our safety comes first on every scene.</Item>
        <Item>If a situation is clearly unfavorable (such as being outnumbered by clearly hostile individuals), avoid calling for law enforcement in front of them. This will give them a reason to attack us, which we would want to avoid at all costs.</Item>
        <Item>Let the EMR know that they need to remember that sometimes patients get upset and they need to be mindful of what they say for their own and all other medics safety.</Item>
        <Item>If possible, return to your vehicle and move about a block away (or 50m+) from the hostile situation.</Item>
        <Item>Once you are a safe distance from the hostile scene, this is when it would be ideal to request for law enforcement over department radio.</Item>
        <Item><OOC>Also mention using <Command>/deplow</Command> instead of <Command>/dep</Command></OOC></Item>
      </Category>
      <Category title="GSB" ordered>
        <Item>Let the EMR know that sometimes GSB will reach out and ask if we require any assistance. Let them know that usually whoever is shift lead will decide whether they&apos;re needed or not. If that is them, then they have the option to tell them they&apos;re unneeded at the moment.</Item>
        <Item>Let them know that GSB is here for our protection and they are NOT to interfere with any patients unless they&apos;re a direct threat to the medic&apos;s life. Even then PD/SD is to be called immediately.</Item>
      </Category>
      <Category title="Treatment Optional: You may use the BLS Classroom for this, provided there is no active BLS Class." ordered>
        <ParagraphList>
          <ParaItem>Ask the EMR how they&apos;d treat the following injuries:</ParaItem>
        </ParagraphList>
        <SubHeading>Closed fracture on a patient&apos;s leg.</SubHeading>
        <BulletList>
          <Item>Gunshot wound located on the patient&apos;s chest.</Item>
          <Item>1st, 2nd, or 3rd-degree burns.</Item>
          <Item>Stab wounds</Item>
          <Item>Concussion</Item>
        </BulletList>
        <Item>
          Explain the process of how to use the stabilize command and explain it is considered powergaming if you stabilize before doing your roleplay to find the injuries on the patient. <Bold>Example</Bold> <Command>/stabilize</Command>
          <BulletList>
            <Item>Ongoing /me&apos;s and /do&apos;s - inspecting and discovering wounds via RP&apos;d response</Item>
            <Item>Followed by /stabilize - upon knowing what treatment you are going to do or provide</Item>
          </BulletList>
          <ParagraphList>
            <ParaItem><Command>/heal</Command></ParaItem>
          </ParagraphList>
          <BulletList>
            <Item>Not allowed to use the command without prior RP.</Item>
            <Item>Ongoing /me&apos;s and /do&apos;s - inspecting and discovering wounds via RP&apos;d response</Item>
            <Item>We use /heal as a reward for good RP. Do not use it if people are asking for a &quot;bandaid&quot; or &quot;icepack&quot; without them actually wanting to do proper RP.</Item>
          </BulletList>
          <ParagraphList>
            <ParaItem><Command>/CPR</Command></ParaItem>
          </ParagraphList>
          <BulletList>
            <Item>Provided after completing a BLS class or passing their certification</Item>
            <Item>Used off duty or by on-duty SD/PD, as well as other people who have a license.</Item>
            <Item>(Ongoing /me&apos;s and /do&apos;s - inspecting and discovering wounds via RP&apos;d response</Item>
            <Item>Misuse of this command will result in the removal of the medical license</Item>
          </BulletList>
        </Item>
      </Category>
      <ParagraphList>
        <ParaItem><Bold>Advanced Treatment</Bold> Explain to the EMR that if there is no AMU around and they want to do more advanced treatment with the help of the doctors we have, they are more than welcome to do so.</ParaItem>
      </ParagraphList>
      <div className="mt-1">
        <OOC>The portion is mostly OOC and is done in cases where the patient brought to a hospital wants to do more advanced treatment RP. Tell the EMR that if AMU is not around and they are willing to do advanced RP, they are more than welcome to do so, as long as the other party wants to do it after asking in <Command>/b</Command>. Here is how it is done, and you will be explaining this to the EMR:</OOC>
      </div>
      <BulletList>
        <Item><OOC>Take the injured player to any hospital. Feel free to drop them off if they are injured or just keep them in the ambulance, however you want to do it.</OOC></Item>
        <Item><OOC>Start doing RP lines along with <Command>/me calls the nurses to come take the patient into the ICU Room.</Command>, <Command>/do The patient would be inside.</Command></OOC></Item>
        <Item><OOC>Do any type of treatment you want. You can say the nurses are doing the RP, the doctors are performing surgery, or go into any kind of depth you&apos;d like, such as removing bullets, bandaging, or even performing surgeries. It will all be done through RP lines with the help of the &quot;doctors&quot; inside of Pillbox, so feel free to go into as much detail as you&apos;d like.</OOC></Item>
        <Item><OOC>After everything is done, you can do <Command>/do The patient would be treated and recovered, then taken out of the ICU and released from the hospital.</Command> or any other line you&apos;d like. If you feel like the RP was good, reward the player with a <Command>/heal</Command>.</OOC></Item>
      </BulletList>
      <ParagraphList>
        <ParaItem><Bold>Methadone</Bold></ParaItem>
      </ParagraphList>
      <BulletList>
        <Item>Instruct the EMR to open the following section in the Department Manual: <BbLink href="https://gov.eclipse-rp.net/viewtopic.php?t=106075#9">7.9 - Methadone</BbLink></Item>
        <Item>Make sure to teach them how to properly do the <Bold>entire procedure</Bold>, especially the importance of utilizing the Prescription Section to note a prescription down.</Item>
        <Item>While looking through the Prescription Section, make sure to remind them that if a someone has been prescribed Methadone in the last 7 days then you cannot prescribe them any, and if they&apos;ve been prescribed 3 times in a single month than you have to be an EMT-I+ to prescribe any further. <Bold>This is of extreme importance, as improperly prescribing Methadone can and will lead to disciplinary action if done incorrectly.</Bold></Item>
        <Item>Inform the EMR that before selling methadone they <Bold>HAVE</Bold> to conduct a drug test.</Item>
        <Item>Inform the EMR that anyone requesting methadone can only pay for it in cash, at the price of $500.</Item>
        <Item>Emphasize the importance of educating the patient about the dangers of an overdose of methadone and inform them that AMU or otherwise are there for further assistance if they seem to be abusing methadone.</Item>
        <Item>Make sure they remember that if they&apos;re unsure on anything that they can contact a Supervisor, Command+ or other personnel.</Item>
        <Item>Go over the Denied Prescription Format with them in detail.</Item>
        <Item><OOC>Inform the EMR roleplay must be completed before using the command, without any roleplay, you&apos;ll be breaking powergaming by forcing roleplay without allowing the other player a chance and abusing faction commands.</OOC></Item>
      </BulletList>
      <Category title="Breathalyser" ordered>
        <Item>Explain to the EMR the process of conducting a breathalyzer on a patient and give them an example of how to do it. <OOC>/breathanalyse</OOC></Item>
        <Item>Inform the EMR that before conducting a breathalyzer they must have the consent of the patient. Explain that if consent is not given, and this is linked to a potential criminal charge, they are required to notify the patient that separate charges can be levied for &apos;Failure to Comply&apos; or potentially &apos;Tampering with Evidence&apos;.</Item>
        <Item>Inform the EMR that if a patient&apos;s blood alcohol percentage is 0.08% and above, they are legally considered intoxicated as per the San Andreas Penal Code.</Item>
        <Item>Remind the EMR that we can offer intoxicated patients water, food, and/or a safe ride home by requesting a taxi or calling a friend depending on the situation. If they witness an intoxicated patient attempting to operate a vehicle following a breathalyzer test, that PD/SD should be contacted via department radio as it poses a risk to their safety and the safety of others.</Item>
        <Item><OOC>Inform the EMR roleplay must be completed before using the command, without any roleplay, you&apos;ll be breaking powergaming by forcing roleplay without allowing the other player a chance and abusing faction commands.</OOC></Item>
      </Category>
      <Category title="Time Management" ordered>
        <ParagraphList>
          <ParaItem>Explain time management to the EMR which means choosing the closest hospital, treating non-critically injured people, and driving Code 3 even when not required if one or more calls are open with nobody to take them.</ParaItem>
        </ParagraphList>
        <SubHeading><OOC>Explain to the EMR when you go more in-depth on treatment in the field.</OOC></SubHeading>
        <BulletList>
          <Item><OOC>Few units, many calls; quick treatment.</OOC></Item>
          <Item><OOC>Many units, few calls; slow and in-depth treatment.</OOC></Item>
        </BulletList>
        <Item>Explain to the EMR that if we are code 3 to call and we approach injured people on the sidewalk, we have to stop.</Item>
        <Item>Inform the EMR that we must drop response to our previous call <OOC>/setcall -1</OOC>, radio call that we are dropping response from our current call, and ask another unit to take the call.</Item>
      </Category>
      <Divider />
      <Divider />
      <Category title="Ending the Phase - Ride-Along" ordered>
        <Item><Bold>Request Call Priority over radio. Either you, or the EMR may do this request.</Bold></Item>
        <Item>If the EMR can do radio calls, unit management, and treatment by themselves, then don&apos;t give them any extra additional mandatory ridealongs.</Item>
        <Item>If you will be 10-8 during your ride-along, take the EMR on a short roam and ask the EMR to do the radio and treatment.</Item>
        <Item>If the EMR doesn&apos;t wish to take any feedback regarding their performance or is struggling on the ridealong, you may assign three to four mandatory ridealongs.</Item>
        <Item>Assign them 1x mandatory ride along, alongside additional mandatories if they require it.</Item>
        <Item><Em><Bold><Underline>If the EMR performed poorly, be honest and genuine on your report</Underline></Bold></Em> - not stating they didn&apos;t do well is only harming the EMR.</Item>
      </Category>
      <Divider />
      <Divider />
    </div>
  );
}
