"use client";
import {
  Bold,
  BulletList,
  Category,
  Command,
  Divider,
  Em,
  EyebrowLabel,
  Item,
  OOC,
  ParagraphList,
  ParaItem,
  Spoiler,
  SubHeading,
  Tinted,
  Underline,
} from "@/app/(routes)/divisions/ftd/paperwork/lib/phase-notes/primitives";
import { Clock } from "lucide-react";
/**
 * The Phase1 guide, built from `docs/handbook/regular/phase-1.txt`.
 *
 * Generated by `npm run notes:build` from that section - edit the handbook,
 * not this file, and run the command again. `npm run notes:check` fails when
 * this Guide has fallen behind the section it is drawn from.
 */
export function Phase1Notes() {
  return (
    <div className="space-y-2.5">
      <div className="rounded-md border border-border/60 bg-muted/30 px-4 py-2.5">
        <EyebrowLabel icon={Clock}>
          PHASE 1 - EMT-I+, 1 Hour Minimum/2 Hour Maximum
        </EyebrowLabel>
      </div>
      <ParagraphList>
        <ParaItem><Bold>THE EMR IS NOT TO DRIVE OR PROVIDE TREATMENT DURING PHASE I. BUT IS REQUIRED TO MANAGE THEIR UNIT</Bold></ParaItem>
      </ParagraphList>
      <Divider />
      <Divider />
      <Category title="Radio Codes" ordered>
        <Item>Explain to the EMR all the different radio codes we have, and what each one of them means</Item>
        <Item>Have them open Section 14.7 of the General Handbook</Item>
        <Item>
          You can find a list of codes here:
          <Spoiler>
            <ParagraphList>
              <ParaItem><Bold>Ten Codes:</Bold></ParaItem>
            </ParagraphList>
            <BulletList>
              <Item><Bold>10-1</Bold> - Roll Call</Item>
              <Item><Bold>10-3</Bold> - Please Stop Transmitting</Item>
              <Item><Bold>10-4</Bold> - Affirmative</Item>
              <Item><Bold>10-5</Bold> - Repeat Last Transmission</Item>
              <Item><Bold>10-6</Bold> - Disregard Last Transmission</Item>
              <Item><Bold>10-8</Bold> - Available</Item>
              <Item><Bold>10-9</Bold> - Unavailable</Item>
              <Item><Bold>10-15</Bold> - Injured Suspect</Item>
              <Item><Bold>10-16</Bold> - Injured Patient</Item>
              <Item><Bold>10-20</Bold> - Location</Item>
              <Item><Bold>10-21</Bold> - Report Status</Item>
              <Item><Bold>10-37</Bold> - Unit Identify</Item>
              <Item><Bold>10-70</Bold> - Backup Request</Item>
              <Item><Bold>10-99</Bold> - Concluded Situation</Item>
            </BulletList>
            <ParagraphList>
              <ParaItem><Bold>Status Codes:</Bold></ParaItem>
            </ParagraphList>
            <BulletList>
              <Item><Bold>Code 0</Bold> - Fell asleep <OOC>Game Crash</OOC></Item>
              <Item><Bold>Code 1</Bold> - Urgent Assistance Required (ALL UNITS)</Item>
              <Item><Bold>Code 2</Bold> - Non-Emergency</Item>
              <Item><Bold>Code 3</Bold> - Emergency</Item>
              <Item><Bold>Code 4</Bold> - No Further Assitance Required</Item>
              <Item><Bold>Code 6</Bold> - On scene</Item>
            </BulletList>
          </Spoiler>
        </Item>
      </Category>
      <Category title="Radio Calls" ordered>
        <Item>Explain to the EMR all the different radio calls we have, and what each one of them means</Item>
        <Item>Point them to Section 14.2 of the General Handbook</Item>
        <Item>
          You can find a list of standard radio calls here:
          <Spoiler>
            <BulletList>
              <Item>
                Getting on shift and starting service under someone:
                <BulletList>
                  <Item>EMR <Bold><Em>[Lastname]</Em></Bold> is starting services under <Bold><Em>[Callsign]</Em></Bold>.</Item>
                </BulletList>
              </Item>
              <Item>
                Getting on shift and forming your own unit:
                <BulletList>
                  <Item>EMR <Bold><Em>[Lastname]</Em></Bold> is forming <Bold><Em>[Callsign]</Em></Bold> and is <Tinted tone="red"><Bold>10-8</Bold></Tinted> from <Tinted tone="red"><Bold>Pillbox</Bold></Tinted>/<Tinted tone="red"><Bold>Paleto</Bold></Tinted>.</Item>
                </BulletList>
              </Item>
              <Item>
                Ending services while under someone:
                <BulletList>
                  <Item>EMR <Bold><Em>[Lastname]</Em></Bold> is leaving <Bold><Em>[Callsign]</Em></Bold> and is <Tinted tone="red"><Bold>10-9</Bold></Tinted> ending services.</Item>
                </BulletList>
              </Item>
              <Item>
                Ending services and disbanding the unit:
                <BulletList>
                  <Item>EMR <Bold><Em>[Lastname]</Em></Bold> is disbanding <Bold><Em>[Callsign]</Em></Bold> and is <Bold><Tinted tone="red">10-9</Tinted></Bold> ending services.</Item>
                </BulletList>
              </Item>
              <Item>
                Radio callout when you arrive on a scene:
                <BulletList>
                  <Item><Bold><Em>[Callsign]</Em></Bold> is <Bold><Tinted tone="red">Code 6</Tinted></Bold> on last call. (<Em>you can say the exact number, but it is not mandatory</Em>)</Item>
                </BulletList>
              </Item>
              <Item>
                Radio callout when you are leaving a scene:
                <BulletList>
                  <Item><Bold><Em>[Callsign]</Em></Bold> is <Tinted tone="red"><Bold>Code 2</Bold></Tinted>/<Tinted tone="red"><Bold>Code 3</Bold></Tinted> to <Tinted tone="red"><Bold>Pillbox</Bold></Tinted>/<Tinted tone="red"><Bold>Paleto</Bold></Tinted>with <Tinted tone="red">X</Tinted> <Tinted tone="red"><Bold>10-15</Bold></Tinted>/<Tinted tone="red"><Bold>10-16</Bold>(&apos;s)</Tinted>from <Tinted tone="red">last call</Tinted>.</Item>
                </BulletList>
              </Item>
              <Item>
                Roaming:
                <BulletList>
                  <Item><Bold><Em>[Callsign]</Em></Bold> is <Bold><Tinted tone="red">10-8</Tinted></Bold> roaming <Bold><Tinted tone="red">[Location]</Tinted></Bold> / <Tinted tone="red"><Bold>[To Location]</Bold></Tinted>.</Item>
                </BulletList>
              </Item>
              <Item>
                Requesting backup:
                <BulletList>
                  <Item><Bold><Em>[Callsign]</Em></Bold> to any <Bold><Tinted tone="red">10-8</Tinted></Bold> units, requesting a <Tinted tone="red"><Bold>10-70</Bold></Tinted> on <Tinted tone="red"><Bold>[Call ID]</Bold></Tinted> / <Bold><Tinted tone="red">[Location]</Tinted></Bold></Item>
                </BulletList>
              </Item>
              <Item>
                Sidewalk encounter or patient:
                <BulletList>
                  <Item><Bold><Em>[Callsign]</Em></Bold> is <Bold><Tinted tone="red">10-9</Tinted></Bold> with a sidewalk patient at <Tinted tone="red"><Bold>[Location]</Bold></Tinted>.</Item>
                </BulletList>
              </Item>
              <Item>
                Dropping response from a call:
                <BulletList>
                  <Item><Bold><Em>[Callsign]</Em></Bold> is dropping response from<Tinted tone="red"><Bold>[Call ID]</Bold></Tinted> and is <Bold><Tinted tone="red">[Status]</Tinted></Bold>.</Item>
                </BulletList>
              </Item>
            </BulletList>
          </Spoiler>
        </Item>
      </Category>
      <Category title="Calls List" ordered>
        <Item>Introduce the EMR to our dispatch system <OOC>/calls</OOC>, inform them that we can see the location, call number, description, and if the call is already taken. <OOC>/calls</OOC></Item>
        <Item>
          Explain how to respond to calls, how to close the call, how to check the location of the call, cross reference this with the next section (Panics &amp; Backups)<OOC>/resp, /closecall, /setcall; make sure to tell them how to utilize /setcall -1 as well</OOC> <Em>You can use a back-up <OOC>/backup</OOC> call to have the EMR practice how to respond, drop response, and close a call</Em>
          <SubHeading>Explain call priority:</SubHeading>
          <BulletList>
            <Item>Injured medics on duty</Item>
            <Item>PD and SD</Item>
            <Item>DOC and GOV</Item>
            <Item>Civilians calls from oldest to the newest</Item>
            <Item>Walk-in patients</Item>
          </BulletList>
        </Item>
        <Item>Inform the EMR that they can close a call if the call is older than one hour. <OOC>Phone time</OOC></Item>
        <Item>Explain to the EMR why calls don&apos;t close by themselves. If the caller was not injured the call will not close.</Item>
        <Item>Explain to the EMR regarding duplicate calls and why we close them.</Item>
        <Item>If your GPS hasn&apos;t updated and is showing the previous call you&apos;ll need to go ahead and clear your GPS. <OOC>/setcall -1</OOC></Item>
        <Item>The callers&apos; phone number will show up in the call log. If there is any trouble, it may help to call the patient.</Item>
      </Category>
      <Category title="Panic Button and Backup Calls" ordered>
        <Item>Explain to the EMR the difference between the panic button and a backup call.</Item>
        <Item>Inform the EMR that if they want to do a backup call, they have to provide a brief summary of the situation. Explain they should also specify if the backup is MD only. <OOC>/backup [text]</OOC></Item>
        <Item>Tell the EMR that if they ask for backup they must stay put at the location as these are associated with their cruiser.</Item>
        <Item>Explain that an EMR&apos;s panic button is connected to the location of their radio. Let them know that panics cannot have reasonings specified when creating them <OOC>CTRL + E</OOC></Item>
        <Item>Let the EMR know that our panics/backups appear in now appear PD / SD dispatch, and if they create a panic/backup for a situation that doesn&apos;t require PD/SD support, they should use the department radio to inform those departments to disregard it. <OOC>/calls</OOC>.</Item>
        <Item>Tell the EMR that if they need help from PD or SD, they should use the department radio and provide them with the backup/panic call number to provide more information. <OOC><Command>/dep</Command></OOC>.</Item>
        <Item>
          Ask the EMR if they would do a backup call or panic based on the following scenarios:
          <BulletList>
            <Item>They flip their ambulance</Item>
            <Item>Armed assailants are standing over their patient(s) and are issuing threats. <OOC>Make sure to remind them of FearRP - they cannot hit a panic while under FearRP!</OOC></Item>
            <Item>They run out of fuel in their ambulance.</Item>
            <Item>They have a severe accident resulting in them getting injured. (Remind them to call 911 to provide information in <Bold>addition to the panic</Bold> if they are unable to reach for their radio!)</Item>
          </BulletList>
        </Item>
      </Category>
      <Category title="Department Radio" ordered>
        <Item>Explain how we use the department radio <OOC><Command>/dep</Command> &amp; <Command>/deplow</Command></OOC>.</Item>
        <Item>Inform the EMR who is on department frequency. (MD, PD, SD, DOC, and GOV branches)</Item>
        <Item>Make sure the EMR knows that department radio has to be answered even if we are 10-9.</Item>
        <Item>Ensure the EMR understands that we always transmit the &quot;MD to&quot; when using department radio.</Item>
        <Item>
          Inform the EMR that we have two different methods for communicating over department radio:
          <BulletList>
            <Item><Em>Non-Urgent:</Em> &quot;MD to PD/SD, how copy?&quot;, then transmit information on their response. Use a few examples for the EMR.</Item>
            <Item><Em>Urgent:</Em> After hitting the panic or backup button, immediately use &quot;MD to PD/SD, need units at [call], [brief reason]&quot;. You skip the &quot;how copy&quot; for urgency&apos;s sake. Provide examples.</Item>
          </BulletList>
        </Item>
        <Item>Inform the EMR that once they are certified, a supervisor(or the highest rank on shift) would usually respond to departmental radio.</Item>
      </Category>
      <Category title="PD/SD Calls" ordered>
        <Item>Inform the EMRs that they need to report when they are en-route over our normal radio, department radio and explain why.</Item>
        <Item>
          Tell the EMR that the first thing to do as they approach the scene is to ask who is injured, who is a 10-15 or 10-16, and if any treatment has been given to the patients before our arrival. (Most PD and SD employees have BLS training)
          <BulletList>
            <Item>If there are no 10-15s, we behave as if it was a normal call.</Item>
            <Item>If there is an injured 10-15, we treat the patient and then we ask PD/SD if we can take the patient to the ambulance and which hospital.</Item>
          </BulletList>
        </Item>
        <Item>
          Explain why:
          <BulletList>
            <Item>Never take 10-15 to the ambulance without PD/SD permission</Item>
            <Item>Never leave a scene without permission from PD/SD</Item>
            <Item>Always ask which hospital PD/SD wants to go</Item>
            <Item>Never drop the patient without asking PD/SD for permission</Item>
          </BulletList>
        </Item>
        <Item>Make sure the EMR knows that it&apos;s better to ask twice than get IA reported for stealing a 10-15.</Item>
        <Item>Explain why sometimes PD/SD calls can be difficult. (Dealing with SD/PD, finding if the patient is a 10-15 or 10-16, checking which hospital you&apos;ll be heading to, and so forth.)</Item>
      </Category>
      <Category title="DOC Calls" ordered>
        <Item>DOC inmates should not be taken out of prison for treatment.</Item>
        <Item>If DOC calls you in to treat an inmate, bring them to the prison&apos;s medical ward and only then treat them. <OOC>Explain that you should then proceed to do regular medical RP alongside a &apos;/stabilize&apos;.<Bold>There is a &apos;/dropbody&apos; point in the medbay, only drop the inmate thereafter both the medical roleplay and &apos;/stabilize&apos; have been completed.</Bold></OOC></Item>
        <Item>A Correctional Officer, or any form of Law Enforcement is <Bold>required</Bold> to be with the medic inside the prison grounds at all times. This is for our safety.</Item>
      </Category>
      <Category title="Specialized Calls" ordered>
        <Item>There will be times when the assistance of a specialized division is required. Generally speaking, we&apos;re thinking of AMU, A&amp;R, and F&amp;R here.</Item>
        <Item>AMU is a division that focuses on advanced medical treatments within hospitals.</Item>
        <Item>A&amp;R (Air &amp; Rescue) is a division that focuses on rescuing from tough-to-reach spots and locations, utilizing helicopters and offroad vehicles.</Item>
        <Item>F&amp;R (Fire &amp; Rescue) is a division that focuses on firefighting and rescuing people from vehicles or objects.</Item>
        <Item>If a situation where the assistance of a specialized unit is required pops up, but none are available, an EMR must know the minimum of what to do.</Item>
        <Item><OOC><Bold>Inform the EMR that if they feel they need to page for AMU or otherwise, the patient has to be asked if they <Em>actually want to do that roleplay</Em> via <Command>/b</Command>. Both of these involve more in-depth character specific RP, and as such, the patient needs to have the time and willingness to do this RP!</Bold></OOC></Item>
        <Item>
          Steps to take if you encounter someone stuck in a tough-to-reach spot and no A&amp;R trained unit is available:
          <BulletList>
            <Item>Get close to the caller with your vehicle, engage the parking brake, and continue on foot.</Item>
            <Item>Make sure you are aware of your surroundings as you attempt to climb up or down to the patient.</Item>
            <Item>Treat them, then carefully get them over to your ambulance.</Item>
          </BulletList>
        </Item>
      </Category>
      <Category title="Fire Calls" ordered>
        <Item>Show the EMR where to retrieve a fire extinguisher. <OOC>RP first, then <Command>/fl</Command> Tell them to press TAB in order to see the hotkey for the extinguisher.</OOC></Item>
        <Item>Then explain the process of extinguishing a fire to the EMR. <OOC><Command>E</Command> on the floating UI, and <Command>/extinguish</Command></OOC></Item>
        <Item>Inform the EMR that there can be lingering flames, and that it&apos;s best to check the surroundings thoroughly. <OOC>Additionally, explain that some fires are glitched and are only visible in the UI when physically close to the fire.</OOC></Item>
        <Item><OOC>Any unattended fires can be handled by roadworkers after 5 minutes, however this does not mean that fires should be left unattended.</OOC></Item>
        <Item>Inform the EMR that these calls do not close themselves, and that it has to be done manually <OOC><Command>/closecall ID</Command></OOC></Item>
        <Item>Finally, have them return the fire extinguisher.</Item>
      </Category>
      <Divider />
      <Divider />
      <Category title="Ending the Phase - Ride-Along" ordered>
        <Item><Bold>Request Call Priority over radio. Either you, or the EMR may do this request.</Bold></Item>
        <Item>Let the EMR take care of unit management, responding to calls, and closing calls.</Item>
        <Item>Ask the EMR if they want to try doing radio codes <OOC>You&apos;ll write them in chat and have them repeat them over the radio</OOC></Item>
        <Item>If the EMR doesn&apos;t want to do the radio try to encourage them.</Item>
        <Item>Explain to the EMR everything that you do and why.</Item>
        <Item>Make sure to say that you are happy with your EMR&apos;s work.</Item>
        <Item>Assign them 1x mandatory ride along, alongside additional mandatories if they require it.</Item>
        <Item><Em><Bold><Underline>If the EMR performed poorly, be honest and genuine on your report</Underline></Bold></Em> - not stating they didn&apos;t do well is only harming the EMR.</Item>
      </Category>
      <Divider />
      <Divider />
    </div>
  );
}
