"use client";
import {
  Bold,
  BulletList,
  Divider,
  Em,
  EyebrowLabel,
  Item,
  NumberedList,
  ParagraphList,
  ParaItem,
  Spoiler,
  Tinted,
  Underline,
  BbLink,
} from "@/app/(routes)/divisions/ftd/paperwork/lib/phase-notes/primitives";
import { Clock } from "lucide-react";
/**
 * The PreCert guide, built from `docs/ftp/regular/pre-certification.txt`.
 *
 * Generated by `npm run notes:build` from that section - edit the FTP,
 * not this file, and run the command again. `npm run notes:check` fails when
 * this Guide has fallen behind the section it is drawn from.
 */
export function PreCertNotes() {
  return (
    <div className="space-y-2.5">
      <div className="rounded-md border border-border/60 bg-muted/30 px-4 py-2.5">
        <EyebrowLabel icon={Clock}>
          PRE-CERTIFICATION - EMT-A+, 1 Hour 30 Min Minimum/3 Hour Maximum
        </EyebrowLabel>
      </div>
      <Divider />
      <Divider />
      <NumberedList>
        <Item>
          <Bold>Beginning</Bold>
          <BulletList>
            <Item>Make sure the EMR has handled and transported a 10-15 during their training, and did it correctly. If this is not the case,<Bold>the EMR cannot pass the Pre-Cert until they treat, handle and transport a 10-15.</Bold></Item>
            <Item>Ask if the EMR has any questions about any of the previous parts of training.</Item>
            <Item>Inform the EMR that during this session, they are on their own unless a crisis occurs or they make a major mistake.</Item>
            <Item>Make sure the EMR creates its own unit and properly does the entire starting shift process without error.</Item>
            <Item>Let the EMR drive an ambulance out of the garage, and inform them that they may station wherever, as well as roam around.</Item>
          </BulletList>
          <Divider />
          <Divider />
        </Item>
        <Item>
          <Bold>During the Pre-Cert</Bold>
          <BulletList>
            <Item><Bold>Request Call and Department Priority over radio. Either you, or the EMR may do this request.</Bold></Item>
            <Item>Observe the EMR, but do not cause total silence, you can and should communicate with them to relax them.</Item>
            <Item>Write feedback on how what the EMR did incorrectly if anything does go wrong.</Item>
            <Item>If the EMR is still having some troubles, make some notes and give them feedback at the end.</Item>
            <Item>Ensure we watch the driving closely and fail if they are a danger when driving the ambulance. If you see them not following proper emergency vehicle protocol while driving, make note of this.</Item>
          </BulletList>
          <Divider />
          <Divider />
        </Item>
        <Item>
          <Bold>Ending</Bold>
          <BulletList>
            <Item><Bold><Tinted tone="red">If the EMR has made a mistake large enough, this is a direct Fail, and they are to do mandatory ride-alongs equal to whatever you decide before re-attempting the pre-certification.</Tinted></Bold></Item>
            <Item>Inform the EMR that they are now able to clock on as EMR-1, EMR-2, and so forth as long as an EMT+I is on duty. If the last EMT+I gets off duty, tell them they should head off as well until someone else clocks on.</Item>
            <Item>Encourage the EMR to do their Certification as soon as possible (within or at around 24 hours after passing Pre-Cert, not required!) while they&apos;re able to retain their confidence.</Item>
            <Item>Inform the EMR that they can also be on shift while they are paired up with an EMT-B, under a Zulu callsign.</Item>
            <Item>Hand them an On-Call Program Pager &amp; explain the program. The EMR is not obliged to join, so do inform them of this as well.</Item>
            <Item>Encourage the EMR to reach out to a Jr. Paramedic+ to schedule their Certification.</Item>
            <Item>Complete the paperwork and make sure to edit the top post with &quot;[Pending Certification] Fname Lname&quot;</Item>
            <Item><Em><Bold><Underline>If the EMR performed poorly, be honest and genuine on your report</Underline></Bold></Em> - not stating they didn&apos;t do well is only harming the EMR.</Item>
          </BulletList>
          <Divider />
          <Divider />
        </Item>
        <Item>
          <Bold>Helpful Questions</Bold>
          <Spoiler title="Helpful Questions">
            <ParagraphList>
              <ParaItem>Did the EMR create a unit? Did the EMR start service correctly? Did the EMR park their ambulance correctly in the ambulance bay? Did the EMR check if there are any calls to take from the call list? Did the EMR respond to calls without you asking to do it? Did the EMR follow call priority? Did the EMR manage to use radio calls properly? Did the EMR respond to department radio if there were any department calls? Did the EMR handle department radio properly and timely? Did the EMR handle PD/SD calls properly? Did the EMR use our MD frequency to radio that they responding to PD/SD calls? Did the EMR ask if the patient is a 10-15 or 10-16? Did the EMR ask if any treatment has been done before? Did the EMR ask if they clear to load the patient to an ambulance if the patient was 10-15? Did the EMR ask PD/SD where they want to go? Did the EMR properly radio transporting a 10-15 Did the EMR ask PD/SD if they clear to drop patients at MD? Did the EMR keep their ambulance locked at all times? Did the EMR properly utilize code 2, 3 and 4? Did the EMR drive properly? Did the EMR know how to utilize all necessary radio calls and codes throughout? Did the EMR treat properly and timely? Did the EMR roam properly and safely?</ParaItem>
            </ParagraphList>
          </Spoiler>
        </Item>
      </NumberedList>
      <ParagraphList>
        <ParaItem><Bold>Note:</Bold> The EMR should <Underline>only</Underline> be <BbLink href="https://pastebin.com/raw/wCL1v4K7">sent</BbLink> the quiz if they <Bold>fail</Bold> their Pre-Certification.</ParaItem>
      </ParagraphList>
    </div>
  );
}
