import type { PromotionRank } from "./types";

export type RankInfo = {
  label: string;
  shortLabel: string;
  emailImg: string;
  personnelImg: string;
  callsignPrefix?: string;
  description: string;
  border: string;
  badge: string;
};

export const rankInfo: Record<PromotionRank, RankInfo> = {
  "emt-b": {
    label: "EMT-Basic",
    shortLabel: "EMT-B",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/JwycCL0R/Gkqft-MR.png",
    callsignPrefix: "E",
    description: "Entry-level EMT certification",
    border: "border-emerald-400/30",
    badge: "bg-emerald-500/20 text-emerald-100 ring-1 ring-emerald-400/40",
  },
  "emt-i": {
    label: "EMT-Intermediate",
    shortLabel: "EMT-I",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/xKgJRkXY/t-SAH1l-A.png",
    callsignPrefix: "E",
    description: "Intermediate EMT qualification",
    border: "border-blue-400/30",
    badge: "bg-blue-500/20 text-blue-100 ring-1 ring-blue-400/40",
  },
  "emt-a": {
    label: "EMT-Advanced",
    shortLabel: "EMT-A",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/gLrjjWg8/Dquo0MQ.png",
    callsignPrefix: "E",
    description: "Advanced EMT with division eligibility",
    border: "border-purple-400/30",
    badge: "bg-purple-500/20 text-purple-100 ring-1 ring-purple-400/40",
  },
  "master-emt": {
    label: "Master EMT",
    shortLabel: "Master",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/8L8c8JJs/z3k86ji.png",
    callsignPrefix: "D",
    description: "Top EMT rank with DELTA callsign",
    border: "border-amber-400/30",
    badge: "bg-amber-500/20 text-amber-100 ring-1 ring-amber-400/40",
  },
  "junior-paramedic": {
    label: "Junior Paramedic",
    shortLabel: "Junior Paramedic",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/8L8c8JJs/z3k86ji.png",
    callsignPrefix: "O",
    description: "Supervisor-in-training",
    border: "border-orange-400/30",
    badge: "bg-orange-500/20 text-orange-100 ring-1 ring-orange-400/40",
  },
  paramedic: {
    label: "Paramedic",
    shortLabel: "Paramedic",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/ycVchNSX/y-JZHa-Kg.png",
    callsignPrefix: "C",
    description: "Full Supervisor rank",
    border: "border-cyan-400/30",
    badge: "bg-cyan-500/20 text-cyan-100 ring-1 ring-cyan-400/40",
  },
  "senior-paramedic": {
    label: "Senior Paramedic",
    shortLabel: "Senior Paramedic",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/rKrkg2WS/Yra8DDl.png",
    callsignPrefix: "C",
    description: "Senior Supervisor rank",
    border: "border-teal-400/30",
    badge: "bg-teal-500/20 text-teal-100 ring-1 ring-teal-400/40",
  },
  "lead-paramedic": {
    label: "Lead Paramedic",
    shortLabel: "Lead Paramedic",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/spQXxzc6/I9A66xq.png",
    callsignPrefix: "C",
    description: "Lead Supervisor rank",
    border: "border-sky-400/30",
    badge: "bg-sky-500/20 text-sky-100 ring-1 ring-sky-400/40",
  },
  lieutenant: {
    label: "Lieutenant",
    shortLabel: "Lieutenant",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/qLfcBLdL/nz-CBN57.png",
    callsignPrefix: "B",
    description: "Command rank",
    border: "border-indigo-400/30",
    badge: "bg-indigo-500/20 text-indigo-100 ring-1 ring-indigo-400/40",
  },
  captain: {
    label: "Captain",
    shortLabel: "Captain",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/Kp7gP9Kh/KVQAs-B8.png",
    callsignPrefix: "B",
    description: "Command rank",
    border: "border-violet-400/30",
    badge: "bg-violet-500/20 text-violet-100 ring-1 ring-violet-400/40",
  },
  commander: {
    label: "Commander",
    shortLabel: "Commander",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/Jj1KMcYB/d-QEQ620.png",
    callsignPrefix: "B",
    description: "Command rank",
    border: "border-fuchsia-400/30",
    badge: "bg-fuchsia-500/20 text-fuchsia-100 ring-1 ring-fuchsia-400/40",
  },
  "deputy-chief": {
    label: "Deputy Chief",
    shortLabel: "Deputy Chief",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/1tR7dDsL/7tg-Puo5.png",
    callsignPrefix: "A",
    description: "High Command rank",
    border: "border-rose-400/30",
    badge: "bg-rose-500/20 text-rose-100 ring-1 ring-rose-400/40",
  },
  "assistant-chief": {
    label: "Assistant Chief",
    shortLabel: "Assistant Chief",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/S8MPKhD/e-Pr6kg-C.png",
    callsignPrefix: "A",
    description: "High Command rank",
    border: "border-pink-400/30",
    badge: "bg-pink-500/20 text-pink-100 ring-1 ring-pink-400/40",
  },
  chief: {
    label: "Chief of EMS",
    shortLabel: "Chief",
    emailImg: "https://i.ibb.co/4wZLh7Hj/C6b52lr.png",
    personnelImg: "https://i.ibb.co/RTX88nSv/o-XLXC5Z.png",
    callsignPrefix: "A",
    description: "Highest rank in LSEMS",
    border: "border-red-400/30",
    badge: "bg-red-500/20 text-red-100 ring-1 ring-red-400/40",
  },
};

export const allRanks: PromotionRank[] = [
  "emt-b",
  "emt-i",
  "emt-a",
  "master-emt",
  "junior-paramedic",
  "paramedic",
  "senior-paramedic",
  "lead-paramedic",
  "lieutenant",
  "captain",
  "commander",
  "deputy-chief",
  "assistant-chief",
  "chief",
];
